title: Things I Find Interesting
description: "Short pieces about things I find interesting - mostly books and biology."
baseurl: "" # the subpath of your site, e.g. /blog

author:
  name:         Sam Deans
  email:        samdeans75@gmail.com
  url:          https://sdeans0.github.io

# Build settings
remote_theme: sdeans0/rain
plugins:
  - jekyll-feed
  - jemoji

# Social media links
social:
  email: samdeans75@gmail.com
  github: https://github.com/sdeans0
  linkedin: https://www.linkedin.com/in/samdeans/
  about: true

permalink:      /:year-:month-:day/:title

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
